export const ENDPOINTS = {
  auth: {
    login: "/accounts/users/login_complete/",
    logout: "/accounts/users/logout/",
    me: "/accounts/users/me/",
    myProfile: "/accounts/users/my-profile/",
    changePassword: "/accounts/users/change_password/",
    forgotPassword: "/accounts/users/forgot_password/",
    resetPasswordConfirm: "/accounts/users/reset_password_confirm/",
  },
  branches: {
    list: "/branches/",
    detail: (id: string | number) => `/branches/${id}/`,
    myBranches: "/branches/my-branches/",
    myBranchesSelect: "/branches/my-branches-select/",
    myDefaultTheme: "/branches/my-default-branch-theme/",
    themeConfig: (id: string | number) => `/branches/${id}/theme-config/`,
    publicLoginThemeByHost: "/branches/public-login-theme/by-host/",
    publicLoginTheme: (slug: string) => `/branches/public-login-theme/${slug}/`,
    publicOrgLoginTheme: (slug: string) => `/branches/public-org-login-theme/${slug}/`,
    users: "/branches/users/",
    userDetail: (id: string | number) => `/branches/users/${id}/`,
    roles: "/branches/roles/",
    branchRoles: (id: string | number) => `/branches/${id}/roles/`,
    organizations: "/branches/organizations/",
    organizationDetail: (id: string | number) => `/branches/organizations/${id}/`,
    organizationStores: (id: string | number) => `/branches/organizations/${id}/stores/`,
    organizationAttachStore: (id: string | number) => `/branches/organizations/${id}/attach-store/`,
    organizationDetachStore: (id: string | number) => `/branches/organizations/${id}/detach-store/`,
    organizationTheme: (id: string | number) => `/branches/organizations/${id}/theme/`,
    organizationAllowedApps: (id: string | number) =>
      `/branches/organizations/${id}/allowed-apps/`,
    organizationRoleApps: (id: string | number) =>
      `/branches/organizations/${id}/role-apps/`,
    organizationSyncVersion: "/branches/organizations/sync-version/",
  },
  users: {
    list: "/accounts/users/",
    detail: (id: string | number) => `/accounts/users/${id}/`,
    createAndAssign: "/accounts/users/create_and_assign/",
    assignToBranch: "/accounts/users/assign_to_branch/",
    changeUserRole: "/accounts/users/change_user_role/",
    toggleGlobalStatus: "/accounts/users/toggle_user_global_status/",
    toggleAssignmentStatus: "/accounts/users/toggle_branch_assignment_status/",
    generatePassword: (id: string | number) => `/accounts/users/${id}/generate-password/`,
    resetPassword: "/accounts/users/reset_password/",
  },
  campaigns: {
    list: "/campaigns/",
    detail: (id: string) => `/campaigns/${id}/`,
    patients: (id: string) => `/campaigns/${id}/patients/`,
    results: (id: string) => `/campaigns/${id}/results/`,
    changeStatus: (id: string) => `/campaigns/${id}/change_status/`,
    duplicate: (id: string) => `/campaigns/${id}/duplicate/`,
    aggregates: "/campaigns/aggregates/",
    hints: "/campaigns/hints/",
  },
  patients: {
    list: "/customers/clients/",
    detail: (id: string) => `/customers/clients/${id}/`,
  },
  conversations: {
    list: "/ai-agents/conversations/",
    detail: (id: string) => `/ai-agents/conversations/${id}/`,
    messages: (id: string) => `/ai-agents/conversations/${id}/messages/`,
    chat: (id: string) => `/ai-agents/conversations/${id}/chat/`,
    /** Cierra conversación del chat interno Studio (canónico). */
    closeConversation: (id: string) => `/ai-agents/conversations/${id}/close-conversation/`,
    /** @deprecated Usar closeConversation. Compat del back. */
    takeControl: (id: string) => `/ai-agents/conversations/${id}/close-conversation/`,
    escalate: (id: string) => `/ai-agents/conversations/${id}/escalate/`,
  },
  unifiedConversations: {
    list: "/ai-agents/unified-conversations/",
    messages: (id: string) => `/ai-agents/unified-conversations/${id}/messages/`,
    reply: (id: string) => `/ai-agents/unified-conversations/${id}/reply/`,
    takeControl: (id: string) => `/ai-agents/unified-conversations/${id}/take_control/`,
    release: (id: string) => `/ai-agents/unified-conversations/${id}/release/`,
    setStatus: (id: string) => `/ai-agents/unified-conversations/${id}/set_status/`,
  },
  opportunities: {
    list: "/services/contracts/",
    detail: (id: string) => `/services/contracts/${id}/`,
    changeStage: (id: string) => `/services/contracts/${id}/change_stage/`,
    markRecovered: (id: string) => `/services/contracts/${id}/mark_recovered/`,
    markLost: (id: string) => `/services/contracts/${id}/mark_lost/`,
    followUp: (id: string) => `/services/contracts/${id}/follow_up/`,
    assign: (id: string) => `/services/contracts/${id}/assign/`,
  },
  analytics: {
    clinicDashboard: "/analytics/dashboard/clinic-dashboard/",
    dashboard: "/analytics/dashboard/complete/",
  },
  config: {
    shared: "/shared/config/",
    unified: "/unified-config/configs/",
  },
  integrations: {
    list: "/ai-agents/external-apis/",
    detail: (id: string) => `/ai-agents/external-apis/${id}/`,
    status: (id: string) => `/ai-agents/external-apis/${id}/status/`,
    testConnection: (id: string) => `/ai-agents/external-apis/${id}/test_connection/`,
    syncSkills: (id: string) => `/ai-agents/external-apis/${id}/sync-skills/`,
  },
  externalApiInstallations: {
    list: "/ai-agents/external-api-installations/",
    detail: (id: string) => `/ai-agents/external-api-installations/${id}/`,
    connect: (id: string) => `/ai-agents/external-api-installations/${id}/connect/`,
    disconnect: (id: string) => `/ai-agents/external-api-installations/${id}/disconnect/`,
  },
  applicationConnections: {
    list: "/ai-agents/application-connections/",
    detail: (id: string) => `/ai-agents/application-connections/${id}/`,
    connect: "/ai-agents/application-connections/connect/",
    credentialFields: (apiId: string) =>
      `/ai-agents/application-connections/credential-fields/${apiId}/`,
  },
  functions: {
    list: "/ai-agents/agent-functions/",
    detail: (id: string) => `/ai-agents/agent-functions/${id}/`,
    execute: (id: string) => `/ai-agents/agent-functions/${id}/execute/`,
    previewFormula: "/ai-agents/agent-functions/preview-formula/",
    previewPython: "/ai-agents/agent-functions/preview-python/",
    resolveIds: (id: string) => `/ai-agents/agent-functions/${id}/resolve-ids/`,
    restore: (id: string) => `/ai-agents/agent-functions/${id}/restore/`,
    stats: (id: string) => `/ai-agents/agent-functions/${id}/stats/`,
    logs: "/ai-agents/function-execution-logs/",
  },
  channels: {
    list: "/ai-agents/channels/",
    detail: (id: string) => `/ai-agents/channels/${id}/`,
    catalog: "/ai-agents/channels/catalog/",
    sendMessage: (id: string) => `/ai-agents/channels/${id}/send_message/`,
    regenerateSecret: (id: string) => `/ai-agents/channels/${id}/regenerate_secret/`,
    simulate: (id: string) => `/ai-agents/channels/${id}/simulate/`,
    sessions: (id: string) => `/ai-agents/channels/${id}/sessions/`,
    testConnection: (id: string) => `/ai-agents/channels/${id}/test_connection/`,
  },
  agents: {
    list: "/ai-agents/agents/",
    detail: (id: string) => `/ai-agents/agents/${id}/`,
    default: "/ai-agents/agents/default/",
    byApp: "/ai-agents/agents/by_app/",
    testLLM: (id: string) => `/ai-agents/agents/${id}/test_llm/`,
    planLimits: "/ai-agents/agents/plan_limits/",
    opsHealth: "/ai-agents/agents/ops-health/",
    skillConfigs: (id: string) => `/ai-agents/agents/${id}/skill-configs/`,
    skillConfig: (id: string, skillId: string) =>
      `/ai-agents/agents/${id}/skill-config/${skillId}/`,
  },
  llm: {
    providers: "/ai-agents/llm-providers/",
    providerDetail: (id: string | number) => `/ai-agents/llm-providers/${id}/`,
    models: "/ai-agents/llm-models/",
    modelDetail: (id: string | number) => `/ai-agents/llm-models/${id}/`,
    chat: "/ai-agents/llm-chat/chat/",
    testConnection: (id: string | number) => `/ai-agents/llm-providers/${id}/test_connection/`,
    testEndpoint: (id: string | number) => `/ai-agents/llm-providers/${id}/test_endpoint/`,
    syncModels: (id: string | number) => `/ai-agents/llm-providers/${id}/sync_models/`,
    modelCapabilities: (id: string | number) => `/ai-agents/llm-providers/${id}/capabilities/`,
    validate: (id: string | number) => `/ai-agents/llm-providers/${id}/validate/`,
  },
  knowledge: {
    list: "/ai-agents/knowledge/",
    detail: (id: string) => `/ai-agents/knowledge/${id}/`,
    search: "/ai-agents/knowledge/search/",
    index: (id: string) => `/ai-agents/knowledge/${id}/index/`,
    reindex: (id: string) => `/ai-agents/knowledge/${id}/reindex/`,
    indexingStatus: (id: string) => `/ai-agents/knowledge/${id}/indexing-status/`,
    unindex: (id: string) => `/ai-agents/knowledge/${id}/unindex/`,
    chunks: (id: string) => `/ai-agents/knowledge/${id}/chunks/`,
    bulkIndex: "/ai-agents/knowledge/bulk_index/",
    bulkCreate: "/ai-agents/knowledge/bulk_create/",
    parseSpreadsheet: "/ai-agents/knowledge/parse_spreadsheet/",
    categories: "/ai-agents/knowledge/categories/",
    categoriesRename: "/ai-agents/knowledge/categories/rename/",
    categoriesDelete: "/ai-agents/knowledge/categories/delete/",
  },
  services: {
    list: "/services/services/",
  },
  scheduling: {
    dashboardSummary: "/scheduling/admin/dashboard/summary/",
    bookings: "/scheduling/admin/bookings/",
  },
  workPlans: {
    list: "/ai-agents/work-plans/",
    detail: (id: string) => `/ai-agents/work-plans/${id}/`,
    createWithItems: "/ai-agents/work-plans/create-with-items/",
    runNext: (id: string) => `/ai-agents/work-plans/${id}/run-next/`,
    runAll: (id: string) => `/ai-agents/work-plans/${id}/run-all/`,
  },
  workItems: {
    list: "/ai-agents/work-items/",
    detail: (id: string) => `/ai-agents/work-items/${id}/`,
    run: (id: string) => `/ai-agents/work-items/${id}/run/`,
    retry: (id: string) => `/ai-agents/work-items/${id}/retry/`,
  },
  workflows: {
    list: "/ai-agents/workflows/",
    detail: (id: string) => `/ai-agents/workflows/${id}/`,
    execute: (id: string) => `/ai-agents/workflows/${id}/execute/`,
    activate: (id: string) => `/ai-agents/workflows/${id}/activate/`,
    deactivate: (id: string) => `/ai-agents/workflows/${id}/deactivate/`,
    triggerTypes: "/ai-agents/workflows/trigger-types/",
  },
  workflowNodes: {
    list: "/ai-agents/workflow-nodes/",
    detail: (id: string) => `/ai-agents/workflow-nodes/${id}/`,
  },
  workflowEdges: {
    list: "/ai-agents/workflow-edges/",
    detail: (id: string) => `/ai-agents/workflow-edges/${id}/`,
  },
  workflowExecutions: {
    list: "/ai-agents/workflow-executions/",
    detail: (id: string) => `/ai-agents/workflow-executions/${id}/`,
  },
} as const;
