export const ENDPOINTS = {
  auth: {
    login: "/accounts/users/login_complete/",
    logout: "/accounts/users/logout/",
    me: "/accounts/users/me/",
    myProfile: "/accounts/users/my-profile/",
  },
  branches: {
    list: "/branches/",
    detail: (id: string | number) => `/branches/${id}/`,
    myBranches: "/branches/my-branches/",
    myBranchesSelect: "/branches/my-branches-select/",
    myDefaultTheme: "/branches/my-default-branch-theme/",
    themeConfig: (id: string | number) => `/branches/${id}/theme-config/`,
    publicLoginThemeByHost: "/branches/public-login-theme/by-host/",
    publicLoginTheme: (slug: string) => `/branches/public-login-theme/${slug}/`,
    publicOrgLoginTheme: (slug: string) => `/branches/public-org-login-theme/${slug}/`,
    users: "/branches/users/",
    userDetail: (id: string | number) => `/branches/users/${id}/`,
    roles: "/branches/roles/",
    organizations: "/branches/organizations/",
    organizationDetail: (id: string | number) => `/branches/organizations/${id}/`,
    organizationStores: (id: string | number) => `/branches/organizations/${id}/stores/`,
  },
  users: {
    list: "/accounts/users/",
    detail: (id: string | number) => `/accounts/users/${id}/`,
    createAndAssign: "/accounts/users/create_and_assign/",
    assignToBranch: "/accounts/users/assign_to_branch/",
    generatePassword: (id: string | number) => `/accounts/users/${id}/generate-password/`,
    resetPassword: "/accounts/users/reset_password/",
  },
  campaigns: {
    list: "/campaigns/",
    detail: (id: string) => `/campaigns/${id}/`,
    patients: (id: string) => `/campaigns/${id}/patients/`,
    results: (id: string) => `/campaigns/${id}/results/`,
    changeStatus: (id: string) => `/campaigns/${id}/change_status/`,
    duplicate: (id: string) => `/campaigns/${id}/duplicate/`,
    aggregates: "/campaigns/aggregates/",
    hints: "/campaigns/hints/",
  },
  patients: {
    list: "/customers/clients/",
    detail: (id: string) => `/customers/clients/${id}/`,
  },
  conversations: {
    list: "/ai-agents/conversations/",
    detail: (id: string) => `/ai-agents/conversations/${id}/`,
    messages: (id: string) => `/ai-agents/conversations/${id}/messages/`,
    chat: (id: string) => `/ai-agents/conversations/${id}/chat/`,
    takeControl: (id: string) => `/ai-agents/conversations/${id}/take_control/`,
    escalate: (id: string) => `/ai-agents/conversations/${id}/escalate/`,
  },
  unifiedConversations: {
    list: "/ai-agents/unified-conversations/",
    messages: (id: string) => `/ai-agents/unified-conversations/${id}/messages/`,
    reply: (id: string) => `/ai-agents/unified-conversations/${id}/reply/`,
    takeControl: (id: string) => `/ai-agents/unified-conversations/${id}/take_control/`,
    setStatus: (id: string) => `/ai-agents/unified-conversations/${id}/set_status/`,
  },
  opportunities: {
    list: "/services/contracts/",
    detail: (id: string) => `/services/contracts/${id}/`,
    changeStage: (id: string) => `/services/contracts/${id}/change_stage/`,
    markRecovered: (id: string) => `/services/contracts/${id}/mark_recovered/`,
    markLost: (id: string) => `/services/contracts/${id}/mark_lost/`,
    followUp: (id: string) => `/services/contracts/${id}/follow_up/`,
    assign: (id: string) => `/services/contracts/${id}/assign/`,
  },
  analytics: {
    clinicDashboard: "/analytics/dashboard/clinic-dashboard/",
    dashboard: "/analytics/dashboard/complete/",
  },
  config: {
    shared: "/shared/config/",
    unified: "/unified-config/configs/",
  },
  integrations: {
    list: "/ai-agents/external-apis/",
    detail: (id: string) => `/ai-agents/external-apis/${id}/`,
    status: (id: string) => `/ai-agents/external-apis/${id}/status/`,
    testConnection: (id: string) => `/ai-agents/external-apis/${id}/test_connection/`,
  },
  functions: {
    list: "/ai-agents/agent-functions/",
    detail: (id: string) => `/ai-agents/agent-functions/${id}/`,
    execute: (id: string) => `/ai-agents/agent-functions/${id}/execute/`,
    logs: "/ai-agents/function-execution-logs/",
  },
  channels: {
    list: "/ai-agents/channels/",
    detail: (id: string) => `/ai-agents/channels/${id}/`,
    catalog: "/ai-agents/channels/catalog/",
    sendMessage: (id: string) => `/ai-agents/channels/${id}/send_message/`,
    regenerateSecret: (id: string) => `/ai-agents/channels/${id}/regenerate_secret/`,
    simulate: (id: string) => `/ai-agents/channels/${id}/simulate/`,
    sessions: (id: string) => `/ai-agents/channels/${id}/sessions/`,
  },
  agents: {
    list: "/ai-agents/agents/",
    detail: (id: string) => `/ai-agents/agents/${id}/`,
    default: "/ai-agents/agents/default/",
    byApp: "/ai-agents/agents/by_app/",
    testLLM: (id: string) => `/ai-agents/agents/${id}/test_llm/`,
    planLimits: "/ai-agents/agents/plan_limits/",
    opsHealth: "/ai-agents/agents/ops-health/",
  },
  llm: {
    providers: "/ai-agents/llm-providers/",
    providerDetail: (id: string | number) => `/ai-agents/llm-providers/${id}/`,
    models: "/ai-agents/llm-models/",
    modelDetail: (id: string | number) => `/ai-agents/llm-models/${id}/`,
    chat: "/ai-agents/llm-chat/chat/",
    testConnection: (id: string | number) => `/ai-agents/llm-providers/${id}/test_connection/`,
    syncModels: (id: string | number) => `/ai-agents/llm-providers/${id}/sync_models/`,
  },
  knowledge: {
    list: "/ai-agents/knowledge/",
    detail: (id: string) => `/ai-agents/knowledge/${id}/`,
    search: "/ai-agents/knowledge/search/",
    index: (id: string) => `/ai-agents/knowledge/${id}/index/`,
    reindex: (id: string) => `/ai-agents/knowledge/${id}/reindex/`,
    unindex: (id: string) => `/ai-agents/knowledge/${id}/unindex/`,
    bulkIndex: "/ai-agents/knowledge/bulk_index/",
    bulkCreate: "/ai-agents/knowledge/bulk_create/",
    parseSpreadsheet: "/ai-agents/knowledge/parse_spreadsheet/",
  },
  services: {
    list: "/services/services/",
  },
  scheduling: {
    dashboardSummary: "/scheduling/admin/dashboard/summary/",
    bookings: "/scheduling/admin/bookings/",
  },
} as const;
